### PR TITLE
midproject

### PR DESCRIPTION
**Pull request by wpan03**
Hi @xavierdong !

I have made the following changes to this repo:

+ Updated  `README.md` to include instructions to get the data and run pipeline for S3 and RDS (See below)
+ Added the dataset in `src/sample/pokemon.csv` and so you can test the uploading for S3
+ I added `run_s3.py` and `run_rds.py` file, which allows you to upload and download file from S3 and create table in RDS. Please see relevant sections in `README.md` to see how to run these two scripts. The functions I used to run these two files are defined in `src/s3.py` and `src/manage_pokemon.py`. Also, the sql url to create table is defined in `config/flaskconfig.py`
+ Include the Dockerfile `Dockerfile_data` to build the image for creating RDS table and uploading data to S3
+ Updated the local logger configuration file (config/logging/local.conf) so that the configurations would apply to logs within modules in src/ while still being able to place the imports at the top of run.py and app.py before defining the logger. (Credit to Chole's PR in the template repo)
+ Included a very basic data cleaning code in `notebooks/develop/00_data_clean.ipynb`
+ Added logger configurations for the Python packages that were producing annoying logs (e.g. boto3) and set them to WARNING level in the local logger configuration file (config/logging/local.conf). (Again, credit to Chole's PR in the template repo)
+ Updated `.gitigore` to ignore credentials and some unnecessary files from python and IDE
+ Removed unnecessary files from the template repo
+ Add a figure to display in `README.md` in `figures/pokemon_show.png`
+ Add relevant requirements for python packages in `requirements.txt`

Please review the files mentioned in the above points. In particular, I want your feedback about whether my logger setting makes sense and whether my instructions in `README.md` to interact with S3 and RDS are clear. Also, make sure to rebuild the Docker image, set relevant environment variables and then run it. Please pay special attention to the logging behavior and make sure what it does make sense.

Thank you!

### CODE REVIEW

**Review by xavierdong — COMMENTED** [review]
this comment regards Dockerfile_data:

you will likely need to include 
CMD ["./app/boot.sh"]
for final app deployment but this fine for this mid project checkpoint

**Review by xavierdong — COMMENTED** [review]
this comment regards Dockerfile_data:
you will likely need to include 
CMD ["./app/boot.sh"]
for final app deployment but this fine for this mid project checkpoint

this comment regards src/manage_pokemon.py:
lime 27: in the Pokemon class, i think you might have forgotten to include id, type1 and type 2 column in def __repr__ to have these attributes in your table's schema, but I do see that you have the add_pokemon function to handle to those user input arguments.

this comment regards run_s3.py:
no edits but including a download argument and function is a good touch that provides user greater functionality

this comment regards READ.ME:
you can consider providing instruction on checking to make sure "pokemons" table is created in pokemon.db and the schema is loaded correctly

**Comment by xavierdong** [comment]
**Functionality**

You have implemented well-thought functions such as add_pokemon and download_s3 which gives the user of your app more flexibility and options when interacting with it.

**Readability & code quality**

Code is easy to read and understand with intuitive use of variables and function names.

**Overall design**

Good use of classes (PokemonManager) to ensure a clean design.

**Documentation**

No problems here, doc-strings and README instruction are easy to read and follow

**Comment by wpan03** [comment]
Hey Xavier, thanks for the suggestions! Those issues should be fixed with the two commit above. Let me know if you have any more questions or issues.

**Pull request merged**
